// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platform.Data;

#nullable disable

namespace Platform.Migrations
{
    [DbContext(typeof(PlatformContext))]
    [Migration("20251230031825_IcommentsTable")]
    partial class IcommentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepartmentUser", b =>
                {
                    b.Property<long>("departmentsid")
                        .HasColumnType("bigint");

                    b.Property<long>("usersid")
                        .HasColumnType("bigint");

                    b.HasKey("departmentsid", "usersid");

                    b.HasIndex("usersid");

                    b.ToTable("DepartmentUser", "iprofile", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Idata.Data.Entities.Iprofile.Department", b =>
                {
                    b.Property<long?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<long?>("depth")
                        .HasColumnType("bigint");

                    b.Property<string>("external_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("is_internal")
                        .HasColumnType("bigint");

                    b.Property<long?>("lft")
                        .HasColumnType("bigint");

                    b.Property<string>("offline_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("options")
                        .HasColumnType("TEXT");

                    b.Property<long?>("organization_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("parent_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("restored_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("restored_by")
                        .HasColumnType("bigint");

                    b.Property<long?>("rgt")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("updated_by")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("departments", "iprofile", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Idata.Data.Entities.Iprofile.Role", b =>
                {
                    b.Property<long?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("external_guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("external_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(191)");

                    b.Property<string>("offline_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("options")
                        .HasColumnType("TEXT");

                    b.Property<string>("permissions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("restored_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("restored_by")
                        .HasColumnType("bigint");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("VARCHAR(191)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("updated_by")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("roles", "iprofile", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Idata.Data.Entities.Iprofile.User", b =>
                {
                    b.Property<long?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(191)");

                    b.Property<Guid?>("external_guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("external_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("VARCHAR(191)");

                    b.Property<string>("language")
                        .HasColumnType("VARCHAR(191)");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .HasColumnType("VARCHAR(191)");

                    b.Property<DateTime?>("last_request")
                        .HasColumnType("datetime2");

                    b.Property<string>("offline_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("options")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(191)");

                    b.Property<string>("permissions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("restored_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("restored_by")
                        .HasColumnType("bigint");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("updated_by")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("users", "iprofile", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Idata.Entities.Icomments.Icomment", b =>
                {
                    b.Property<long?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("id"));

                    b.Property<bool?>("approved")
                        .HasColumnType("bit");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<long?>("commentable_id")
                        .HasColumnType("bigint");

                    b.Property<string>("commentable_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<string>("external_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guest_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guest_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_internal")
                        .HasColumnType("bit");

                    b.Property<string>("offline_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("options")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("restored_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("restored_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Icomments", "icomments");
                });

            modelBuilder.Entity("Idata.Entities.Iprofile.AuthClient", b =>
                {
                    b.Property<long?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<string>("device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("external_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("impersonated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("last_request")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("offline_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("options")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("refreshed_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("restored_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("restored_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("revoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<long?>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("impersonated_by");

                    b.HasIndex("user_id");

                    b.ToTable("AuthClients", "iprofile", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("rolesid")
                        .HasColumnType("bigint");

                    b.Property<long>("usersid")
                        .HasColumnType("bigint");

                    b.HasKey("rolesid", "usersid");

                    b.HasIndex("usersid");

                    b.ToTable("RoleUser", "iprofile", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("DepartmentUser", b =>
                {
                    b.HasOne("Idata.Data.Entities.Iprofile.Department", null)
                        .WithMany()
                        .HasForeignKey("departmentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Idata.Data.Entities.Iprofile.User", null)
                        .WithMany()
                        .HasForeignKey("usersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idata.Entities.Icomments.Icomment", b =>
                {
                    b.HasOne("Idata.Data.Entities.Iprofile.User", "userProfile")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("userProfile");
                });

            modelBuilder.Entity("Idata.Entities.Iprofile.AuthClient", b =>
                {
                    b.HasOne("Idata.Data.Entities.Iprofile.User", "impersonator")
                        .WithMany()
                        .HasForeignKey("impersonated_by");

                    b.HasOne("Idata.Data.Entities.Iprofile.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("impersonator");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Idata.Data.Entities.Iprofile.Role", null)
                        .WithMany()
                        .HasForeignKey("rolesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Idata.Data.Entities.Iprofile.User", null)
                        .WithMany()
                        .HasForeignKey("usersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
